//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigma_Trainer.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sigma_Trainer.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🍎 Add a post.
        /// </summary>
        internal static string Add_a_post {
            get {
                return ResourceManager.GetString("Add a post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a score ➕.
        /// </summary>
        internal static string Add_a_score {
            get {
                return ResourceManager.GetString("Add a score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exercise.
        /// </summary>
        internal static string AddExercise {
            get {
                return ResourceManager.GetString("AddExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the exercise?.
        /// </summary>
        internal static string DeleteExerciseAnswer {
            get {
                return ResourceManager.GetString("DeleteExerciseAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new name:.
        /// </summary>
        internal static string Enter_a_new_name {
            get {
                return ResourceManager.GetString("Enter a new name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of points:.
        /// </summary>
        internal static string Enter_the_number_of_points_ {
            get {
                return ResourceManager.GetString("Enter the number of points:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden.
        /// </summary>
        internal static string Golden {
            get {
                return ResourceManager.GetString("Golden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My exercises.
        /// </summary>
        internal static string My_exercises {
            get {
                return ResourceManager.GetString("My exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New exercise.
        /// </summary>
        internal static string NewExercise {
            get {
                return ResourceManager.GetString("NewExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull-ups.
        /// </summary>
        internal static string Pull_ups {
            get {
                return ResourceManager.GetString("Pull-ups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push-ups.
        /// </summary>
        internal static string Push_ups {
            get {
                return ResourceManager.GetString("Push-ups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename exercise.
        /// </summary>
        internal static string Rename_exercise {
            get {
                return ResourceManager.GetString("Rename exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a theme.
        /// </summary>
        internal static string Select_a_theme {
            get {
                return ResourceManager.GetString("Select a theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language and restart applications to apply!.
        /// </summary>
        internal static string Select_language {
            get {
                return ResourceManager.GetString("Select language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squats.
        /// </summary>
        internal static string Squats {
            get {
                return ResourceManager.GetString("Squats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme settings.
        /// </summary>
        internal static string Theme_settings {
            get {
                return ResourceManager.GetString("Theme settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone!!!.
        /// </summary>
        internal static string This_action_cannot_be_undone_ {
            get {
                return ResourceManager.GetString("This action cannot be undone!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        internal static string Workouts {
            get {
                return ResourceManager.GetString("Workouts", resourceCulture);
            }
        }
    }
}
